### ISSUE TITLE
How to get a snapshot of website

### ISSUE THREAD

**Issue by Takanakesi** [AhmadChaiban/Malicious-Website-Feature-Study#1]
## Abstract
I don't know how to take a snapshot of the websites contained in the GAWAIN dataset.
If the website is online, I can take a snapshot by using  "image_extraction.py".
However there many websites that are not online.

## Sugestion
This project deals with image embedding. 
So you should have a raw snapshot of the website included in the GAWAIN dataset.
If possible, please publish the raw snapshot to Google Drive.

**Comment by AhmadChaiban** [comment]
Hi, sorry for the late reply on this. At the time of the publication I missed adding a folder for the benign images. The issue was that a lot of the websites at the time of the study were already taken down, so I managed to get around 90-100 thousand snapshots from that dataset. You can find them here [Images on Google drive](https://drive.google.com/drive/folders/1LXJDSe1f4sfqHdsvXWo3D9YrdcAz5iNq). Hope this helps!
